names:
  GR4J:
    Airsnow_Coeff: Airsnow_Coeff
    Cemaneige_X1: Cemaneige_x1
    Cemaneige_X2: Cemaneige_x2
    GR4J_X1: GR4J_x1
    GR4J_X1b: Soil_0
    GR4J_X2: GR4J_x2
    GR4J_X3: GR4J_x3
    GR4J_X4: GR4J_x4
  HBV:
    HBV_Param_01: RainSnow_Temp
    HBV_Param_02: Melt_Fact
    HBV_Param_03: Refreeze_Fact
    HBV_Param_04: Snow_SWI
    HBV_Param_05: Porosity
    HBV_Param_06: Field_Cap
    HBV_Param_07: HBV_Beta
    HBV_Param_08: Max_Perc_Rate_Fast_Res
    HBV_Param_09: BaseFlow_Coeff_Fast_Res
    HBV_Param_10: BaseFlow_Coeff_Slow_Res
    HBV_Param_11: T_Conc_Max_Bas
    HBV_Param_11b: HBV_Para_11b
    HBV_Param_12: Prec_Lapse_PCALT
    HBV_Param_13: Adiab_Lapse_TCALT
    HBV_Param_14: Sat_Wilt
    HBV_Param_15: Alpha
    HBV_Param_16: Max_Cap_Rise_Rate
    HBV_Param_17: Thickness_Topsoil
    HBV_Param_17b: HBV_Para_17b
    HBV_Param_18: HBV_Melt_For_Corr
    HBV_Param_19: Glac_Storage_Effect
    HBV_Param_20: Rain_Correction_RFCF
    HBV_Param_21: Snow_Correction_SFCF
  HMETS:
    HMETS_Param_01: HMETS_Param_01 #GAMMA_SHAPE
    HMETS_Param_02: HMETS_Param_02 #GAMMA_SCALE
    HMETS_Param_03: HMETS_Param_03 #GAMMA_SHAPE2
    HMETS_Param_04: HMETS_Param_04 #GAMMA_SCALE2
    HMETS_Param_05a: HMETS_Param_05a #MIN_MELT_FACTOR
    HMETS_Param_05b: HMETS_Param_05b #HMETS_Param_05b
    HMETS_Param_06: HMETS_Param_06 #HMETS_Param_06
    HMETS_Param_07: HMETS_Param_07 #DD_MELT_TEMP
    HMETS_Param_08: HMETS_Param_08 #DD_AGGRADATION
    HMETS_Param_09a: HMETS_Param_09a #SNOW_SWI_MIN
    HMETS_Param_09b: HMETS_Param_09b #HMETS_Param_09b
    HMETS_Param_10: HMETS_Param_10 #HMETS_Param_10
    HMETS_Param_11: HMETS_Param_11 #SWI_REDUCT_COEFF
    HMETS_Param_12: HMETS_Param_12 #DD_REFREEZE_TEMP
    HMETS_Param_13: HMETS_Param_13 #REFREEZE_FACTOR
    HMETS_Param_14: HMETS_Param_14 #REFREEZE_EXP
    HMETS_Param_15: HMETS_Param_15 #PET_CORRECTION_TOPSOIL
    HMETS_Param_16: HMETS_Param_16 #HMETS_RUNOFF_COEFF
    HMETS_Param_17: HMETS_Param_17 #PERC_COEFF_TOPSOIL
    HMETS_Param_18: HMETS_Param_18 #BASEFLOW_COEFF_TOPSOIL
    HMETS_Param_19: HMETS_Param_19 #BASEFLOW_COEFF_PHREATIC
    HMETS_Param_20a: HMETS_Param_20a #HMETS_Param_20
    HMETS_Param_20b: HMETS_Param_20b #HMETS_Param_20b
    HMETS_Param_21a: HMETS_Param_21a #HMETS_Param_21
    HMETS_Param_21b: HMETS_Param_21b #HMETS_Param_21b
  HYMOD:
    HYMOD_Param_01: Res_Constant
    HYMOD_Param_02: C_max
    HYMOD_Param_03: T_s
    HYMOD_Param_04: K_s
    HYMOD_Param_05: Melt_Factor
    HYMOD_Param_06: DD_Melt_Temp
    HYMOD_Param_07: B_exp
    HYMOD_Param_08: PET_Correction
    HYMOD_Param_09: ALPHA
  MOHYSE:
    MOHYSE_Param_01: MOHYSE_PARAM_01
    MOHYSE_Param_02: MOHYSE_PARAM_02
    MOHYSE_Param_03: MOHYSE_PARAM_03
    MOHYSE_Param_04: MOHYSE_PARAM_04
    MOHYSE_Param_05: MOHYSE_PARAM_05
    MOHYSE_Param_06: MOHYSE_PARAM_06
    MOHYSE_Param_07: MOHYSE_PARAM_07
    MOHYSE_Param_08: MOHYSE_PARAM_08
    MOHYSE_Param_09: MOHYSE_PARAM_09
    MOHYSE_Param_10: MOHYSE_PARAM_10
params:
  GR4J:
    Airsnow_Coeff: '0.5'
    Cemaneige_X1: '0.5'
    Cemaneige_X2: '0.5'
    GR4J_X1: '0.5'
    GR4J_X1b: '500'
    GR4J_X2: '0.5'
    GR4J_X3: '0.5'
    GR4J_X4: '0.5'
  HBV:
    HBV_Param_01: '0.5'
    HBV_Param_02: '0.5'
    HBV_Param_03: '0.5'
    HBV_Param_04: '0.5'
    HBV_Param_05: '0.5'
    HBV_Param_06: '0.5'
    HBV_Param_07: '0.5'
    HBV_Param_08: '0.5'
    HBV_Param_09: '0.5'
    HBV_Param_10: '0.5'
    HBV_Param_11: '0.5'
    HBV_Param_11b: '0.5'
    HBV_Param_12: '0.5'
    HBV_Param_13: '0.5'
    HBV_Param_14: '0.5'
    HBV_Param_15: '0.5'
    HBV_Param_16: '0.5'
    HBV_Param_17: '0.5'
    HBV_Param_17b: '0.5'
    HBV_Param_18: '0.5'
    HBV_Param_19: '0.5'
    HBV_Param_20: '0.5'
    HBV_Param_21: '0.5'
  HMETS:
    HMETS_Param_01: '0.5'
    HMETS_Param_02: '0.5'
    HMETS_Param_03: '0.5'
    HMETS_Param_04: '0.5'
    HMETS_Param_05a: '0.5'
    HMETS_Param_05b: '0.5'
    HMETS_Param_06: '0.5'
    HMETS_Param_07: '0.5'
    HMETS_Param_08: '0.5'
    HMETS_Param_09a: '0.5'
    HMETS_Param_09b: '0.5'
    HMETS_Param_10: '0.5'
    HMETS_Param_11: '0.5'
    HMETS_Param_12: '0.5'
    HMETS_Param_13: '0.5'
    HMETS_Param_14: '0.5'
    HMETS_Param_15: '0.5'
    HMETS_Param_16: '0.5'
    HMETS_Param_17: '0.5'
    HMETS_Param_18: '0.5'
    HMETS_Param_19: '0.5'
    HMETS_Param_20a: '0.5'
    HMETS_Param_20b: '155'
    HMETS_Param_21a: '0.5'
    HMETS_Param_21b: '458'
  HYMOD:
    HYMOD_Param_01: '0.5'
    HYMOD_Param_02: '0.5'
    HYMOD_Param_03: '0.5'
    HYMOD_Param_04: '0.5'
    HYMOD_Param_05: '0.5'
    HYMOD_Param_06: '0.5'
    HYMOD_Param_07: '0.5'
    HYMOD_Param_08: '0.5'
    HYMOD_Param_09: '0.5'
  MOHYSE:
    MOHYSE_Param_01: '0.5'
    MOHYSE_Param_02: '0.5'
    MOHYSE_Param_03: '0.5'
    MOHYSE_Param_04: '0.5'
    MOHYSE_Param_05: '0.5'
    MOHYSE_Param_06: '0.5'
    MOHYSE_Param_07: '0.5'
    MOHYSE_Param_08: '0.5'
    MOHYSE_Param_09: '0.5'
    MOHYSE_Param_10: '0.5'
